### ISSUE TITLE
Add heap.Meld to interface definition

### ISSUE THREAD

**Issue by erjiaqing** [theodesp/go-heaps#24]
Many heaps supports the meld operation in O(log n) or even O(1) time complexity, and some heaps are designed for fast meld operation.

**Comment by theodesp** [comment]
Hey. is it meld similar to merge? because if it is then we the tricky part is to make it work with all implementations. For example:

LeftList
--
```
https://github.com/theodesp/go-heaps/blob/master/leftlist/leftist_heap.go#L35
```

Skew
--
https://github.com/theodesp/go-heaps/blob/master/skew/skew_heap.go#L18

Pairing
--
https://github.com/theodesp/go-heaps/blob/master/pairing/pairing_heap.go#L227

So we have different signatures unless we have a generic node type we can use.

**Comment by theodesp** [comment]
We need to introduce an invariant to check if b is from the same heap or from a different one first.
Something similar to:
https://github.com/google/btree/blob/master/btree.go#L592

Then depending on that we can do either a merge or do a clone + insert

**Comment by theodesp** [comment]
Meld is added with this commit
https://github.com/theodesp/go-heaps/commit/d25b436491812d3dcc2e672ba4336ddc7075149d
